# Use root/example as user/password credentials
version: '3.1'

services:
  inventoryman:
    image: inventoryman
    restart: always
    ports:
    - 5000:3000
    environment:
      SESSION_SECRET: sanju
      db_name: warehousedb
      db_user_name: root
      db_password: example
      login_id: sanju.g1@gmail.com
      login_password: Sanju@123
      PORT: 3000
